export const ErrorCodes = {
  // Auth
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  INVALID_TOKEN: 'INVALID_TOKEN',
  EMAIL_NOT_VERIFIED: 'EMAIL_NOT_VERIFIED',
  EMAIL_TAKEN: 'EMAIL_TAKEN',
  WEAK_PASSWORD: 'WEAK_PASSWORD',
  BANNED: 'BANNED',
  SUSPENDED: 'SUSPENDED',
  ACCOUNT_SUSPENDED: 'ACCOUNT_SUSPENDED',
  ACCOUNT_PENDING: 'ACCOUNT_PENDING',
  ACCOUNT_REJECTED: 'ACCOUNT_REJECTED',

  // Validation
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  DUPLICATE_EMAIL: 'DUPLICATE_EMAIL',
  DUPLICATE_BID: 'DUPLICATE_BID',

  // Resources
  NOT_FOUND: 'NOT_FOUND',
  JOB_EXPIRED: 'JOB_EXPIRED',
  JOB_FILLED: 'JOB_FILLED',
  JOB_CLOSED: 'JOB_CLOSED',
  BID_LOCKED: 'BID_LOCKED',
  BID_NOT_PENDING: 'BID_NOT_PENDING',
  BOOKING_ACTIVE: 'BOOKING_ACTIVE',
  THREAD_LOCKED: 'THREAD_LOCKED',

  // Business logic
  UNDERAGE: 'UNDERAGE',
  SHOOT_DATE_NOT_PASSED: 'SHOOT_DATE_NOT_PASSED',
  DISPUTE_WINDOW_CLOSED: 'DISPUTE_WINDOW_CLOSED',
  DISPUTE_ALREADY_EXISTS: 'DISPUTE_ALREADY_EXISTS',
  PAYMENT_FAILED: 'PAYMENT_FAILED',
  CONTRACT_NOT_SIGNED: 'CONTRACT_NOT_SIGNED',
  CONTRACT_ALREADY_SIGNED: 'CONTRACT_ALREADY_SIGNED',
  INVALID_STATE: 'INVALID_STATE',
  HOURS_REQUIRED_FOR_HOURLY: 'HOURS_REQUIRED_FOR_HOURLY',
  MIN_PORTFOLIO_REQUIRED: 'MIN_PORTFOLIO_REQUIRED',
  CONFLICT: 'CONFLICT',

  // Throttling
  RATE_LIMITED: 'RATE_LIMITED',
  CAPTCHA_REQUIRED: 'CAPTCHA_REQUIRED',
  CAPTCHA_FAILED: 'CAPTCHA_FAILED',

  // Caster subscription billing
  SUBSCRIPTION_REQUIRED: 'SUBSCRIPTION_REQUIRED',

  // Server
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes]
