import type { Prisma } from '@prisma/client'
import { GetObjectCommand, PutObjectCommand } from '@aws-sdk/client-s3'
import { getSignedUrl } from '@aws-sdk/s3-request-presigner'
import type {
  PresignedUrlInput,
  ConfirmUploadInput,
  UpdatePortfolioItemInput,
} from '@castflow/validators'
import { UPLOAD_LIMITS } from '@castflow/validators'
import { prisma } from '../lib/prisma'
import { r2, Buckets } from '../lib/r2'
import { env } from '../lib/env'
import { AppError } from '../errors'

type UploadType = PresignedUrlInput['type']

function bucketFor(type: UploadType): { bucket: string; visibility: 'public' | 'private' } {
  if (type === 'id_document') return { bucket: Buckets.private, visibility: 'private' }
  return { bucket: Buckets.public, visibility: 'public' }
}

function keyFor(type: UploadType, userId: string, ext: string): string {
  const safeExt = ext.replace(/[^a-z0-9]/gi, '') || 'bin'
  return `${type}/${userId}/${crypto.randomUUID()}.${safeExt}`
}

function extFromContentType(contentType: string): string {
  return contentType.split('/')[1] ?? 'bin'
}

export class UploadService {
  protected static readonly db = prisma

  static async getPresignedUrl(userId: string, input: PresignedUrlInput) {
    const limits = UPLOAD_LIMITS[input.type]
    const allowed: readonly string[] = limits.types
    if (!allowed.includes(input.contentType)) {
      throw new AppError('VALIDATION_ERROR', 'Unsupported file type', 400, {
        contentType: [`Allowed: ${limits.types.join(', ')}`],
      })
    }
    const maxBytes = limits.maxSizeMb * 1024 * 1024
    if (input.size > maxBytes) {
      throw new AppError('VALIDATION_ERROR', 'File too large', 400, {
        size: [`Max ${limits.maxSizeMb} MB`],
      })
    }

    const { bucket, visibility } = bucketFor(input.type)
    const key = keyFor(input.type, userId, extFromContentType(input.contentType))

    const command = new PutObjectCommand({
      Bucket: bucket,
      Key: key,
      ContentType: input.contentType,
      ContentLength: input.size,
    })

    const uploadUrl = await getSignedUrl(r2, command, { expiresIn: 60 * 5 })
    const publicUrl =
      visibility === 'public' ? `${env.R2_PUBLIC_URL.replace(/\/$/, '')}/${key}` : null

    return {
      uploadUrl,
      publicUrl,
      key,
      bucket,
      visibility,
      expiresIn: 60 * 5,
    }
  }

  /**
   * Confirm a client upload. Trusts the client + verifies later on read.
   * Portfolio uploads → create PortfolioItem; ID doc → patch profile.
   *
   * Key-ownership check: the R2 object key is server-generated by `getPresignedUrl`
   * with the prefix `${type}/${userId}/`. We reject any confirm whose key does not
   * match that prefix so a malicious client cannot graft someone else's URL/key
   * onto their own profile or portfolio.
   */
  static async confirmUpload(userId: string, input: ConfirmUploadInput) {
    const expectedPrefix = `${input.type}/${userId}/`
    if (!input.key.startsWith(expectedPrefix)) {
      throw new AppError('FORBIDDEN', 'Upload key does not belong to this user', 403)
    }

    // Public URL is derivable from the key for public buckets; the client may
    // pass it for convenience but we re-derive to avoid trusting client input.
    const publicUrl = `${env.R2_PUBLIC_URL.replace(/\/$/, '')}/${input.key}`

    if (input.type === 'portfolio_photo' || input.type === 'portfolio_video') {
      const profile = await prisma.artistProfile.findUnique({
        where: { userId },
        select: { id: true, portfolioItems: { select: { id: true, isPrimary: true } } },
      })
      if (!profile) throw new AppError('NOT_FOUND', 'Artist profile not found', 404)

      const setAsPrimary = input.isPrimary ?? profile.portfolioItems.length === 0

      const item = await prisma.$transaction(async (tx) => {
        if (setAsPrimary) {
          await tx.portfolioItem.updateMany({
            where: { artistProfileId: profile.id, isPrimary: true },
            data: { isPrimary: false },
          })
        }
        return tx.portfolioItem.create({
          data: {
            artistProfileId: profile.id,
            type: input.type === 'portfolio_photo' ? 'photo' : 'video',
            entryType: input.entryType ?? 'other',
            url: publicUrl,
            title: input.title ?? null,
            description: input.description ?? null,
            links: input.links ?? [],
            caption: input.caption ?? null,
            displayOrder: profile.portfolioItems.length,
            isPrimary: setAsPrimary,
            isApproved: false,
          },
        })
      })
      return { kind: 'portfolio_item' as const, item }
    }

    if (input.type === 'id_document') {
      const profile = await prisma.artistProfile.findUnique({
        where: { userId },
        select: { id: true },
      })
      if (!profile) throw new AppError('NOT_FOUND', 'Artist profile not found', 404)
      await prisma.artistProfile.update({
        where: { id: profile.id },
        data: { idDocumentUrl: input.key, idVerified: false },
      })
      return { kind: 'id_document' as const, key: input.key }
    }

    if (input.type === 'caster_logo') {
      const profile = await prisma.casterProfile.findUnique({
        where: { userId },
        select: { id: true },
      })
      if (!profile) throw new AppError('NOT_FOUND', 'Caster profile not found', 404)
      await prisma.casterProfile.update({
        where: { id: profile.id },
        data: { logoUrl: publicUrl },
      })
      return { kind: 'caster_logo' as const, url: publicUrl }
    }

    return { kind: 'noop' as const, url: input.url ?? publicUrl }
  }

  /**
   * Delete a portfolio item. Only the artist who owns the item can delete it.
   * If the deleted item was primary, promote the next one (lowest displayOrder)
   * to primary so the profile always has a primary while items exist.
   */
  static async deletePortfolioItem(userId: string, itemId: string) {
    const item = await prisma.portfolioItem.findUnique({
      where: { id: itemId },
      select: {
        id: true,
        isPrimary: true,
        artistProfile: { select: { userId: true, id: true } },
      },
    })
    if (!item) throw new AppError('NOT_FOUND', 'Portfolio item not found', 404)
    if (item.artistProfile.userId !== userId) {
      throw new AppError('FORBIDDEN', 'You do not own this portfolio item', 403)
    }

    await prisma.$transaction(async (tx) => {
      await tx.portfolioItem.delete({ where: { id: itemId } })
      if (item.isPrimary) {
        const next = await tx.portfolioItem.findFirst({
          where: { artistProfileId: item.artistProfile.id },
          orderBy: { displayOrder: 'asc' },
          select: { id: true },
        })
        if (next) {
          await tx.portfolioItem.update({
            where: { id: next.id },
            data: { isPrimary: true },
          })
        }
      }
    })
    return { deleted: true as const, id: itemId }
  }

  /**
   * Short-lived presigned GET for the calling artist's OWN ID document. Only
   * the owner can call this; the URL is single-use-ish (10 min lifetime) so
   * even if the artist's session is shoulder-surfed the URL expires fast.
   * Admins read ID docs through the admin surface, not this endpoint. (H14.)
   */
  static async getMyIdDocumentUrl(userId: string): Promise<{
    url: string
    expiresIn: number
    contentTypeHint: 'image' | 'pdf' | 'unknown'
  } | null> {
    const profile = await prisma.artistProfile.findUnique({
      where: { userId },
      select: { idDocumentUrl: true },
    })
    if (!profile?.idDocumentUrl) return null
    const key = profile.idDocumentUrl
    const command = new GetObjectCommand({ Bucket: Buckets.private, Key: key })
    const expiresIn = 60 * 10
    const url = await getSignedUrl(r2, command, { expiresIn })
    const lower = key.toLowerCase()
    const contentTypeHint: 'image' | 'pdf' | 'unknown' = lower.endsWith('.pdf')
      ? 'pdf'
      : /\.(jpe?g|png)$/.test(lower)
        ? 'image'
        : 'unknown'
    return { url, expiresIn, contentTypeHint }
  }

  /**
   * Admin-only: short-lived presigned read URL for an applicant's ID document,
   * looked up by ArtistProfile id (not userId). Used by the application-review
   * screen to view the uploaded ID securely — expires in 10 minutes and is
   * never persisted into the app's own storage.
   */
  static async getIdDocumentUrlByProfileId(profileId: string): Promise<{
    url: string
    expiresIn: number
    contentTypeHint: 'image' | 'pdf' | 'unknown'
  } | null> {
    const profile = await prisma.artistProfile.findUnique({
      where: { id: profileId },
      select: { idDocumentUrl: true },
    })
    if (!profile?.idDocumentUrl) return null
    const key = profile.idDocumentUrl
    const command = new GetObjectCommand({ Bucket: Buckets.private, Key: key })
    const expiresIn = 60 * 10
    const url = await getSignedUrl(r2, command, { expiresIn })
    const lower = key.toLowerCase()
    const contentTypeHint: 'image' | 'pdf' | 'unknown' = lower.endsWith('.pdf')
      ? 'pdf'
      : /\.(jpe?g|png)$/.test(lower)
        ? 'image'
        : 'unknown'
    return { url, expiresIn, contentTypeHint }
  }

  /**
   * Edit an existing portfolio entry's metadata (entryType/title/description/
   * links/caption). The image itself is fixed at upload time. Empty strings
   * clear the field. Only the owning artist may edit.
   */
  static async updatePortfolioItem(
    userId: string,
    itemId: string,
    input: UpdatePortfolioItemInput
  ) {
    const item = await prisma.portfolioItem.findUnique({
      where: { id: itemId },
      select: { id: true, artistProfile: { select: { userId: true } } },
    })
    if (!item) throw new AppError('NOT_FOUND', 'Portfolio item not found', 404)
    if (item.artistProfile.userId !== userId) {
      throw new AppError('FORBIDDEN', 'You do not own this portfolio item', 403)
    }

    const data: Prisma.PortfolioItemUpdateInput = {}
    if (input.entryType !== undefined) data.entryType = input.entryType
    if (input.title !== undefined) data.title = input.title === '' ? null : input.title
    if (input.description !== undefined)
      data.description = input.description === '' ? null : input.description
    if (input.links !== undefined) data.links = input.links
    if (input.caption !== undefined) data.caption = input.caption === '' ? null : input.caption

    return prisma.portfolioItem.update({ where: { id: itemId }, data })
  }

  static async setPrimaryPortfolioItem(userId: string, itemId: string) {
    const item = await prisma.portfolioItem.findUnique({
      where: { id: itemId },
      select: { id: true, artistProfile: { select: { userId: true, id: true } } },
    })
    if (!item) throw new AppError('NOT_FOUND', 'Portfolio item not found', 404)
    if (item.artistProfile.userId !== userId) {
      throw new AppError('FORBIDDEN', 'You do not own this portfolio item', 403)
    }
    await prisma.$transaction(async (tx) => {
      await tx.portfolioItem.updateMany({
        where: { artistProfileId: item.artistProfile.id, isPrimary: true },
        data: { isPrimary: false },
      })
      await tx.portfolioItem.update({ where: { id: itemId }, data: { isPrimary: true } })
    })
    return { id: itemId, isPrimary: true }
  }
}
