import { PutObjectCommand } from '@aws-sdk/client-s3'
import { getSignedUrl } from '@aws-sdk/s3-request-presigner'
import type { PresignedUrlInput, ConfirmUploadInput } from '@castflow/validators'
import { UPLOAD_LIMITS } from '@castflow/validators'
import { prisma } from '../lib/prisma'
import { r2, Buckets } from '../lib/r2'
import { env } from '../lib/env'
import { AppError } from '../errors'

type UploadType = PresignedUrlInput['type']

function bucketFor(type: UploadType): { bucket: string; visibility: 'public' | 'private' } {
  if (type === 'id_document') return { bucket: Buckets.private, visibility: 'private' }
  return { bucket: Buckets.public, visibility: 'public' }
}

function keyFor(type: UploadType, userId: string, ext: string): string {
  const safeExt = ext.replace(/[^a-z0-9]/gi, '') || 'bin'
  return `${type}/${userId}/${crypto.randomUUID()}.${safeExt}`
}

function extFromContentType(contentType: string): string {
  return contentType.split('/')[1] ?? 'bin'
}

export class UploadService {
  protected static readonly db = prisma

  static async getPresignedUrl(userId: string, input: PresignedUrlInput) {
    const limits = UPLOAD_LIMITS[input.type]
    const allowed: readonly string[] = limits.types
    if (!allowed.includes(input.contentType)) {
      throw new AppError('VALIDATION_ERROR', 'Unsupported file type', 400, {
        contentType: [`Allowed: ${limits.types.join(', ')}`],
      })
    }
    const maxBytes = limits.maxSizeMb * 1024 * 1024
    if (input.size > maxBytes) {
      throw new AppError('VALIDATION_ERROR', 'File too large', 400, {
        size: [`Max ${limits.maxSizeMb} MB`],
      })
    }

    const { bucket, visibility } = bucketFor(input.type)
    const key = keyFor(input.type, userId, extFromContentType(input.contentType))

    const command = new PutObjectCommand({
      Bucket: bucket,
      Key: key,
      ContentType: input.contentType,
      ContentLength: input.size,
    })

    const uploadUrl = await getSignedUrl(r2, command, { expiresIn: 60 * 5 })
    const publicUrl =
      visibility === 'public' ? `${env.R2_PUBLIC_URL.replace(/\/$/, '')}/${key}` : null

    return {
      uploadUrl,
      publicUrl,
      key,
      bucket,
      visibility,
      expiresIn: 60 * 5,
    }
  }

  /**
   * Confirm a client upload. Trusts the client + verifies later on read.
   * Portfolio uploads → create PortfolioItem; ID doc → patch profile.
   *
   * Key-ownership check: the R2 object key is server-generated by `getPresignedUrl`
   * with the prefix `${type}/${userId}/`. We reject any confirm whose key does not
   * match that prefix so a malicious client cannot graft someone else's URL/key
   * onto their own profile or portfolio.
   */
  static async confirmUpload(userId: string, input: ConfirmUploadInput) {
    const expectedPrefix = `${input.type}/${userId}/`
    if (!input.key.startsWith(expectedPrefix)) {
      throw new AppError('FORBIDDEN', 'Upload key does not belong to this user', 403)
    }

    if (input.type === 'portfolio_photo' || input.type === 'portfolio_video') {
      const profile = await prisma.artistProfile.findUnique({
        where: { userId },
        select: { id: true, portfolioItems: { select: { id: true } } },
      })
      if (!profile) throw new AppError('NOT_FOUND', 'Artist profile not found', 404)

      const item = await prisma.portfolioItem.create({
        data: {
          artistProfileId: profile.id,
          type: input.type === 'portfolio_photo' ? 'photo' : 'video',
          url: input.url,
          displayOrder: profile.portfolioItems.length,
          isPrimary: profile.portfolioItems.length === 0,
          isApproved: false,
        },
      })
      return { kind: 'portfolio_item' as const, item }
    }

    if (input.type === 'id_document') {
      const profile = await prisma.artistProfile.findUnique({
        where: { userId },
        select: { id: true },
      })
      if (!profile) throw new AppError('NOT_FOUND', 'Artist profile not found', 404)
      await prisma.artistProfile.update({
        where: { id: profile.id },
        data: { idDocumentUrl: input.key, idVerified: false },
      })
      return { kind: 'id_document' as const, key: input.key }
    }

    return { kind: 'noop' as const, url: input.url }
  }
}
