export type UserRole = 'admin' | 'caster' | 'artist'
export type UserStatus = 'pending' | 'active' | 'suspended' | 'banned'
export type ArtistType = 'model' | 'actor'
export type ApprovalStatus = 'pending' | 'approved' | 'rejected'
export type ExperienceLevel = 'new_face' | 'semi_pro' | 'professional'
export type AvailabilityStatus = 'available' | 'unavailable'
export type SkinTone = 'fair' | 'light' | 'medium' | 'olive' | 'tan' | 'deep'

export type JobCategory = 'model' | 'actor' | 'voiceover' | 'extra'
export type JobStatus = 'draft' | 'active' | 'filled' | 'expired' | 'cancelled' | 'closed'
export type JobVisibility = 'public' | 'invite_only'

// The two payment types — like Upwork
// fixed: flat fee for the whole shoot (e.g. £500)
// hourly: per-hour rate × agreed hours (e.g. £85/hr × 8hrs = £680)
export type JobPaymentType = 'fixed' | 'hourly'

// Whether the caster sets the rate or leaves it open for artists to propose
export type RateSetBy = 'caster' | 'open'

export type BidStatus =
  | 'pending'
  | 'shortlisted'
  | 'rejected'
  | 'accepted'
  | 'withdrawn'
  | 'expired'
export type BookingStatus = 'pending_payment' | 'confirmed' | 'completed' | 'cancelled' | 'disputed'
export type EscrowStatus =
  | 'awaiting_payment'
  | 'held'
  | 'released'
  | 'refunded'
  | 'partially_refunded'
  | 'disputed'
export type ContractStatus = 'pending_signatures' | 'partially_signed' | 'fully_signed' | 'voided'
export type DisputeReason =
  | 'no_show_artist'
  | 'no_show_caster'
  | 'payment_issue'
  | 'quality_issue'
  | 'other'
export type DisputeStatus = 'open' | 'under_review' | 'resolved' | 'escalated'
export type DisputeResolution =
  | 'full_release_to_artist'
  | 'full_refund_to_caster'
  | 'split'
  | 'escalated'
export type PortfolioItemType = 'photo' | 'video'
export type CompanyType = 'brand' | 'agency' | 'production_house' | 'independent'
export type InviteStatus = 'pending' | 'accepted' | 'declined'
export type CancelledBy = 'caster' | 'artist'
export type ReviewerRole = 'caster' | 'artist'
export type UploadType =
  | 'portfolio_photo'
  | 'portfolio_video'
  | 'id_document'
  | 'demo_reel'
  | 'caster_logo'
  | 'job_cover'

export type NotificationType =
  | 'artist_approved'
  | 'artist_rejected'
  | 'bid_received'
  | 'bid_shortlisted'
  | 'bid_rejected'
  | 'bid_accepted'
  | 'bid_expired'
  | 'booking_confirmed'
  | 'booking_cancelled_by_caster'
  | 'booking_cancelled_by_artist'
  | 'contract_ready'
  | 'contract_signed_by_other'
  | 'contract_fully_signed'
  | 'payment_held'
  | 'payment_released'
  | 'payment_failed'
  | 'payout_sent'
  | 'dispute_opened'
  | 'dispute_resolved'
  | 'message_received'
  | 'job_matching_posted'
  | 'job_expiring_soon'
  | 'job_expired'
  | 'review_received'
